<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
	<title>礼品兑换券管理后台</title>
	<link href="media/css/bootstrap.min.css" rel="stylesheet">
    <link href="media/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="media/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="media/css/style.css" rel="stylesheet" type="text/css"/>
    <link href="media/css/style-responsive.css" rel="stylesheet" type="text/css"/>
    <link href="media/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>
    <link href="media/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css" />
    <link href="static/css/giftwxapp.css" rel="stylesheet" type="text/css">
    <script src="media/js/jquery-1.10.1.min.js" type="text/javascript"></script>
    <script src="media/js/jquery.dotdotdot.js"></script>
    <script src="media/js/bootstrap.min.js"></script>
    <script src="media/js/bootstrap-datetimepicker.js"></script>
    <script src="media/js/nice-validator/jquery.validator.js?local=zh-CN"></script>
    <script src="media/js-ext/common.js" type="text/javascript"></script>
    <script src="media/js/common-module.js" type="text/javascript"></script>
    <style> * { font-family: "arial", "微软雅黑"; } </style>
</head>
<body class="page-header-fixed page-sidebar-fixed">
    <div class="header navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="brand" href="/index" style="padding-left: 10px;">
                    <i class="icon-truck"></i>礼品兑换券管理后台</a>
                <a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
                    <img src="media/image/menu-toggler.png" alt="" /></a>
                <ul class="nav pull-right" style="margin-right: 10px;">
                    <li>
                        <a href="javascript:void(0)">您好，亲爱的宋志辉</a></li>
                    <li>
                        <a href="/index/pLogout">退出</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="page-container " style="">
        <div class="page-sidebar nav-collapse collapse">
            <ul class="page-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="icon-folder-close"></i>
                        <span class="arrow"></span>兑换商品
                    </a>
                    <ul class="sub-menu">
                        <li class="">
                            <a class="" href="/">
                                <i class="icon-file"></i>礼品包管理
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            <ul class="page-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="icon-folder-close"></i>
                        <span class="arrow"></span>兑换券管理</a>
                    <ul class="sub-menu">
                        <li class="">
                            <a class="" href="/ticket/add">
                                <i class="icon-file"></i>兑换券发行</a>
                        </li>
                        <li class="">
                            <a class="" href="/ticket/list">
                                <i class="icon-file"></i>兑换券列表</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <ul class="page-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="icon-folder-close"></i>
                        <span class="arrow"></span>兑换信息</a>
                    <ul class="sub-menu">
                        <li class="">
                            <a class="" href="/">
                                <i class="icon-file"></i>兑换信息详情</a>
                        </li>
                        <li class="">
                            <a class="" href="/">
                                <i class="icon-file"></i>兑换信息列表</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <ul class="page-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="icon-folder-close"></i>
                        <span class="arrow"></span>权限管理</a>
                    <ul class="sub-menu">
                        <li class="">
                            <a class="" href="/user/index">
                                <i class="icon-file"></i>用户管理</a>
                        </li>
                        <li class="">
                            <a class="" href="/group/index">
                                <i class="icon-file"></i>角色管理</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <ul class="page-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="icon-folder-close"></i>
                        <span class="arrow"></span>系统管理</a>
                    <ul class="sub-menu">
                        <li class="">
                            <a class="" href="/system/index">
                                <i class="icon-file"></i>操作日志</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="page-content" style="min-height: 680px;">
            <div class="container-fluid text-center">
                <h3 class="m-t-40">宋志辉，您好！欢迎使用礼品兑换</h3>
            </div>
        </div>
    </div>
    <!-- <div class="footer" style="background-color: #000; margin-left: 0; ">
        <div class="footer-inner">2018 © Market by Xidibuy.</div>
        <div class="footer-tools"></div>
    </div> -->
    <script src="media/js/app-sidebar.js"></script>
</body>
</html>
